#+TITLE: Ad Nom 2

* Wir sind wichtige leute.
We are important people.

* Wir sind stacke Frauen.
We are strong women.

* Wann sind zusätsliche untersuchungen notwendig?
When are additional tests necessary?

* Der höchste Berg von Afrika.
The highest moutain of Africa.

* Die starken Schüler tragen den Tisch.
The strong pupils are carrying the table.

* Das sind unterschiedliche Tassen.
These are different cups.

* Das sind externe Mitarbeiter.
These are external employees.

* Was ist größer als der höchste Berg?
What is larger than the highest mountain?

* Wo ist der höchste Berg dieser Insel?
Where is the highest mountain of this island?

* Das sind die neuesten Opfer.
These are the newest victims.

* Das sind günstige Hüte.
These are cheap hats.

* Der ehemalige Bahnhof ist jetzt ein Restaurant.
The former train station is now a restaurant.

* Wie ist deine neue Freudin?
What is your new girlfriend like?

* Wie geht's deiner neuen Freundin?
How is your new girlfriend?

* Eine neue Bahn
a new train

* die ähnlichen Hunde
the similar dogs

* Der Nächste, bitte!
Next, please!

* Die jungen Leute hören nicht mehr auf ihre Eltern.
The young people do not listen to their parents anymore.

* Ein öffenliches Gebäude is für alle.
A public building is for everyone.

* Der Mensch ist ein soziales Tier.
Man is a social animal.

* Er macht soziale Arbeit.
He does social work.

* Ein Deutscher steht am Fenster.
A German is standing at the window.
