#+TITLE: Adjectives 5

* Ich treffe gern neue Leute.
I like meeting new people.

* Er mag den Deutschen Wein.
He likes the German wine.

* Wir mögen den Deutschen Experten.
We like the german expert.

* Die Frau mag die detaillierte Antwort.
The woman like the detailed answer.

* Nehmen Sie den neuen Weg!
Take the new path!

* Ich habe ein neues Farrad.
I have a new bicycle.

* Mutter, ich will kein neues Kleid!
Mother, I don't want a new dress!

* Ich nehme den nächsten Bus.
I am taking the next bus.

* Wir haben zwei neue Fahrräder.
We have two new bicycles.

* Was machen Sie nächsten Sonntag?
What are you doing next Sunday?

* Sie hat einen Deutschen Hut.
She has a German hat.

* Ihr seid die neuen Studenten.
You are the new students.

* Ich trage ein neues Paar schuhe.
I am wearing a new pair of shoes.
** das Paar -> ein neues Paar

* Duo kauft jede Woche ein neues Flugzeug.
Duo buys a new plane every week.

* Er nimmt alle verfügbaren Kleider.
He talks all available dresses.

* Er seht die verschiedenen Tiere.
He sees the different animals.

* Was sind deine Wünsche für das neue Jahr?
What are your wishes for the new year?

* Hast du diese neue Buch?
Do you have this new book?

* Wo seid so lange gewesen?
Where have you been for so long?

* Auf neue Freunde.
To new friends. (A toast)
