#+TITLE: Conditional Perfect

* Er hätte euch beraten.
He would have advised you.

* Sie hätte die Katze behalten.
She could have kept the cat.

* Sie sagten, sie hätten dieses Auto nicht geprüft.
They said they would not have tested this car.

* Wir hätten den Kindergarten geprüft.
We would have examined the kindergarten.

* Wir hätten eure Texte niemals veröffentliched.
We would have never published your texts.

* Ich hätte ihr Buch nicht veröffentliched.
I would have not published her book.

* Wir hätten alles erfahren.
We would have found out everyting.

* Du hättest ihn verlassen.
You would have left him.

* Ich hätte das Auto behalten.
I would have kept the car.

* Wir dachten, du hättest uns verlassen.
We thought you had left us.

* Hätte er den Hund behalten?
Would he have kept the dog?

* Wir wären für immer Freunde gewesen.
We woul have been friends forever.

* Er hätte es mir nicht gesagt.
He would not have told me.

* Ich hätte etwas gesagt.
I would have said something.

* Wärst du gekommen?
Would you have come?

* Das wäre gut gewesen.
That would have been good.

* Ich hätte es Ihnen gesagt.
I would have told you.

* Ich hätte nein gesagt.
I would have said no.

* Ich dachte, es wären mehr gewesen.
I thought there would have been more.

* Wir hätten es Ihnen gesagt.
We would have told you.

* Sie wären für ihn bereit gewesen.
They would have been ready for him.

* Es wären nur ein paar Minuten gewesen.
It would have been only a few minutes.

* Sie wären für ihn gut gewesen.
They would have been good for him.
