#+TITLE: Dative 1

* Die Enkelin schenkt ihrer Großmutter eine Blume.
The granddaughter gives a flower to her grandmother.
** shencken (to give, to gift)

* Wir geben das Spielzeug dem zweiten Sohn.
We are giving the toy to the second son.

* In dem gesamten Haus gibt es drei Fenster.
The entire house has three windows.

* Ich spreche mit dem gesamten Personal.
I am talking to the entire staff.

* Ich spiele mit den deutschen Kindern.
I am playing with the german children.

* Wir spazieren mit einer bekannten Person.
We are walking with a famous person.
** bekannt (known, famouse)

* Wir spaziren mit den alten Frauen.
We are strolling with the old women.

* Wir schenken der gesamten Familie Wein.
We are giving the whole family wine.

* Ich esse mit drei bekannten Personen in unserem Restaurant.
I am eating with three famous person in our restaurant.

* Sprichst du mit der bekannten Ärztin?
Are you talking to the famous doctor?

* Sie schenkt ihn ein Schwein.
She gives him a pig.

* Was passiert mit den privaten Daten?
What happens to the private data?

* Was passiert an einem ganz normalen Tag?
What happens on a totally normal day?

* Das Gemüse kommt aus verschiedennen Regionen.
The vegetables come from different regions.

* Ich spreche von normalen Häusern!
I speak of normal houses!

* Er spricht von den vergangenen Tagen.
He is talking about the past days.

* Sie ist jetzt in ihrer eigenen Welt.
She is now in her own world.

* Ich sage das aus persönlichen Grüden.
I am saying this for personal reasons.

* Wie geht es der heutigen Umwelt?
How is today's environment?

* Er ersetzt alles mit persönlichen Namen.
He replaces everything with personal names.
