#+TITLE: Future Perfect

* Sie werden geschlossen haben.
They will have closed.

* Sie werden das Buch gelesen haben.
You will have read the book.

* Die Tür wird geschlossen sein.
The door will be closed.

* das Internet
the internet

* Ich werden morgen mehr gelesen haben.
I have have read more tomorrow.

* Dieser Bahnhof wird ab morgen geschlossen sein.
This train station will be closed after tomorrow.

* Er wird gefahren sein.
He will have driven.

* Ich werde in der Woche gefahren sein.
I will have driven in that week.

* Am Dienstag werde ich das Buch gelesen haben.
I will have read the book on Tuesday.

* Wirst du schon gegessen haben?
Will you have eaten already?

* Wirst du die Milch morgen gekauft haben?
Will you have bought the milk tomorrow?

* Wohin wird er gegangen sein?
Where will he have gone?

* Wird er es dem Freund gesagt haben?
Will he have told the friend?

* Werdet ihr schon gegangen sein?
Will you have gone already?

* Im Dezember werdet ihr das Product gekauft haben.
You will have bought the product in December.

* Wenn du kommst, werde ich gegessen haben.
When you come, I will have eaten.

* Was wird er gesagt haben?
What will he have said?

* Sie werden gegangen sein.
You will have left.

* Werdet ihr um sechs Uhr gegessen haben?
Will you have eaten at six o'clock?

* Wir werden die Bücher bald gekauft haben.
We will have bought the books soon.
