#+TITLE: Genitive Case

* Der Junge singt während des Fluges.
The boy sings during the flight.

* Ich trinke währen der Nacht.
I am dring during the night.

* Ich lese die Zeitung der Frau.
I am reading the woman's newspaper.

* Das ist der Weg des Herzens.
That is the way of the heart.

* Das ist die Dame des Hauses.
This is the laday of the house.

* Dezember ist der letzte Monate des Jahres.
December is the last month of the year.

* Das ist das Haus der Großeltern.
That is the house of the grandparents.

* Das ist die letzte Stunde des Tages.
That is the last hour of the day.

* Ihr seid das Salz der Erde.
You are the salt of the earth.
** salt of the earth (a really honest and worthy person)

* Juni ist ein Monat des Jahres.
June is a month of the year.

* Freitag is der fünfte Tag der Woche.
Friday is the fifth day of the week.

* Während der Ferien mache ich nichts.
I am not doing anything during the vocations.

* Ich bin auf dem Balkon des Hauses.
I am on the balcony of the house.

* Der Hund der Frau ist alt.
The woman's dog is old.

* Die Farbe des Teppichs ist komisch.
The color of the carpet is strange.

* Die Farben des Vereins sind blau und schwarz.
The colors of the club are blue and black.

* Er ist der Vater ihrer Freundin.
He is her friend's father.

* Er trägt den Hut seiner Freundin.
He is wearing his girlfriend's hat.

* Er ist der Sohn meiner Schwester.
He is my sister's son.

* Die Diät meiner großmutter ist schlecht.
My grandmother's diet is bad.

* Ich bin die Tochter meiner Eltern.
I am my parents' daughter.

* Der Mund des Kindes ist offen.
The child's mouth is open.

* Die Katze dieser Frau ist weiß.
This woman's cat is white.

* Sie lernt mit den Kindern ihrer Freunde.
She is studying with her friends' children.

* Das ist das Auto deiner Schwester.
This is your sister's car.

* Wie ist der Name deiner Lehrerin?
What is your teacher's name?

* Sie gehen zum Haus meines Vaters.
They go to my father's house.

* Ich bin der Vater ihres Sohnes.
I am her son's father.

* Das Dach meines Hauses ist rot.
The roof of my house is read.

* Das Hemd des Mannes ist klein.
The man's shirt is small.

* Das ist das Haus dieses Mannes.
That is this man's house.

* Das ist der Alkohol meiner Großeltern.
That is my grandparents' alcohol.

* Das ist der Gast seiner Mitarbeiterin.
That is his colleagues's guest.
